const randomTaskList = [
  {
    assignee: "Rutvik",
    description: "make greed",
    id: 1,
    status: "Todo",
    title: "Learn Css",
  },
  {
    assignee: "Rutvik",
    description: "make greed",
    id: 2,
    status: "Todo",
    title: "Learn Css",
  },
  {
    assignee: "Deep",
    description: "make greed",
    id: 3,
    status: "Todo",
    title: "Learn Css",
  },
  {
    assignee: "Deep",
    description: "make greed",
    id: 4,
    status: "Todo",
    title: "Learn Css",
  },
  {
    assignee: "Deep",
    description: "make greed",
    id: 5,
    status: "In Progress",
    title: "Learn Css",
  },
  {
    assignee: "Manish",
    description: "make greed",
    id: 6,
    status: "In Progress",
    title: "Learn Css",
  },
  {
    assignee: "Manish",
    description: "make greed",
    id: 7,
    status: "In Progress",
    title: "Learn Css",
  },
  {
    assignee: "Shiv",
    description: "make greed",
    id: 8,
    status: "In Progress",
    title: "Learn Css",
  },
  {
    assignee: "Manish",
    description: "make greed",
    id: 9,
    status: "In Progress",
    title: "Learn Css",
  },
  {
    assignee: "Rutvik",
    description: "make greed",
    id: 10,
    status: "Done",
    title: "Learn Css",
  },
  {
    assignee: "Shiv",
    description: "make greed",
    id: 11,
    status: "Done",
    title: "Learn Css",
  },
  {
    assignee: "Shiv",
    description: "make greed",
    id: 12,
    status: "Done",
    title: "Learn Css",
  },
  {
    assignee: "Shiv",
    description: "make greed",
    id: 13,
    status: "Done",
    title: "Learn Css",
  },
  {
    assignee: "Shiv",
    description: "make greed",
    id: 14,
    status: "Done",
    title: "Learn Css",
  },
  {
    assignee: "Yash",
    description: "make greed",
    id: 15,
    status: "Todo",
    title: "Learn Css",
  },
  {
    assignee: "Yash",
    description: "make greed",
    id: 16,
    status: "Todo",
    title: "Learn Css",
  },
  {
    assignee: "Yash",
    description: "make greed",
    id: 17,
    status: "Done",
    title: "Learn Css",
  },
  {
    assignee: "Yash",
    description: "make greed",
    id: 18,
    status: "Done",
    title: "Learn Css",
  },
];
export default randomTaskList;
